### ISSUE TITLE
Song stops when we hit the back button

### ISSUE THREAD

**Issue by hdoria** [jsagorin/iOSBackgroundAudio#3]
Hi, 

Song stops playing when we hit the back button. When we select a song it goes to the DetailViewController and the song starts playing, but the song stops when going back to MasterViewContoller. What should I do to keep the music playing?

**Comment by jsagorin** [comment]
Hi,

For this demo, testMusicPlayer is an instance of DetailViewController. When DetailViewController is de-scoped, so is the TestMusicPlayer instance, so the audio is stopped. 

You could create a singleton music player, or create an instance of music player on your app Delegate. The music will continue to play.  

(I'd probably go with the singleton implementation)

**Comment by hdoria** [comment]
Worked! Thanks. :)

**Comment by jsagorin** [comment]
Excellent! Glad I could help.
